["NIRI CORE"]
packages = [
    "niri",
    "xwayland-satellite",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-gnome",
    
]

["UTILIDADES"]
packages = [
    "brightnessctl",
    "power-profiles-daemon",
    "swayidle",           # gestor de inactividad para Wayland
]

