["RED Y SEGURIDAD"]
packages = [
    "bind",               # herramientas DNS (incluye nslookup)
    "hcxdumptool",        # herramienta de captura WiFi
    "hcxtools",           # herramientas para an√°lisis WiFi
    "wireshark-cli",      # analizador de protocolos de red (CLI)
    "wifite",             # herramienta de captura WiFi
    "rustscan",           # herramienta de escaneo de red
    "nmap",               # herramienta de escaneo de red
]
