# Lista de herramientas de terminal para Arch Linux

["SISTEMA BASE"]
packages = [
    "git",                # control de versiones
    "openssh",            # cliente/servidor SSH
    "base-devel",         # herramientas de desarrollo básicas
]

["TERMINAL Y SHELL"]
packages = [
    "fish",               # shell moderno
    "kitty",              # emulador de terminal
    "starship",           # prompt personalizable
]

["HERRAMIENTAS MODERNAS"]
packages = [
    "eza",                # listado de archivos mejorado
    "duf",                # información de discos mejorada
    "zoxide",             # navegación de directorios inteligente
    "fzf",                # buscador difuso
    "ripgrep",            # búsqueda en texto
    "fd",                 # búsqueda de archivos
    "less",               # visor de texto
    "bat",                # cat mejorado
]

["EDITORES"]
packages = [
    "neovim",             # editor de texto avanzado
]



["UTILIDADES"]
packages = [
    "jq",                 # procesador JSON
    "curl",               # cliente web
    "wget",               # descargador web

]

["MONITORES Y SISTEMA"]
packages = [
    "htop",               # monitor de procesos
    "fastfetch",          # información del sistema
    "ncdu",               # visor de uso de disco en terminal
]

["CONTENEDORES"]
packages = [
    "docker",             # contenedores
]



