# Lista de paquetes generales del sistema (compartidos entre i3 y Hyprland)
# Nota: Las herramientas de terminal están en pkg_arch.toml y pkg_ubuntu.toml
["EDITORES Y DESARROLLO"]
packages = [
    "cursor-bin",         # IDE moderno
]

["LENGUAJES Y RUNTIME"]
packages = [
    "uv",                 # gestor de paquetes Python
]

["HERRAMIENTAS Y UTILIDADES"]
packages = [
    "gnome-keyring",      # gestor de claves y contraseñas
    "udiskie",            # montaje automático de medios
]

["THEMING Y CONFIGURACIÓN"]
packages = [
    "noto-fonts-emoji",   # fuente emoji
    "ttf-jetbrains-mono-nerd",  # fuente nerdfont
    "ttf-roboto",         # fuente sans-serif
    "ttf-ms-fonts",       # fuente Microsoft
    "ttf-wps-fonts",          # fuente de WPS Office
]

["CURSORES E ICONOS"]
packages = [
    "bibata-cursor-theme",      # tema de cursor Bibata (Bibata-Modern-Ice)
    "papirus-icon-theme",       # tema de iconos Papirus
]
