["SWAY CORE"]
packages = [
    "sway",
    "swayidle",
    "xwayland-satellite",
    "xdg-desktop-portal",
    "xdg-desktop-portal-wlr",
    "xdg-desktop-portal-gnome",
]

["DMS SHELL Y DEPENDENCIAS"]
packages = [
    "dms-shell-bin",
    "quickshell",
    "matugen-git",
    "dgop",
    "dsearch",
    "hyprpicker",
]

["CLIPBOARD"]
packages = [
    "wl-clipboard",
    "cliphist",
    "wl-paste",
]

["SCREENSHOTS"]
packages = [
    "grim",
    "slurp",
]

["AUDIO Y MULTIMEDIA"]
packages = [
    "wireplumber",
    "playerctl",
]

["TERMINAL Y APLICACIONES"]
packages = [
    "kitty",
    "dolphin",
]

["FUENTES Y EXTRAS"]
packages = [
    "ttf-roboto",
    "ttf-jetbrains-mono-nerd",
    "ttf-ms-fonts",
    "inter-font",
    "gpu-screen-recorder",
    "wlsunset",
]

["SOPORTE QT/WAYLAND"]
packages = [
    "qt5-wayland",
    "qt6-wayland",
    "polkit-kde-agent",
]

["UTILIDADES"]
packages = [
    "brightnessctl",
    "trash-cli",
]

["TEMAS Y APARIENCIA"]
packages = [
    "papirus-icon-theme",
    "bibata-cursor-theme",         # tema de cursor minimalista
]

