# Lista de aplicaciones Flatpak organizadas por categorías



["JUEGOS Y GAMING"]
packages = [
    "com.valvesoftware.Steam",
    "com.valvesoftware.Steam.CompatibilityTool.Proton-GE",
    "net.lutris.Lutris",
]


["MULTIMEDIA - REPRODUCTORES"]
packages = [
    "org.videolan.VLC",
    "com.spotify.Client",
]

["MULTIMEDIA - EDICIÓN"]
packages = [
    "com.obsproject.Studio",
    "com.github.unrud.VideoDownloader",
    "com.github.jesec.FreeTube",
]

["PRODUCTIVIDAD Y OFICINA"]
packages = [
    "com.wps.Office",
]

["COMUNICACIÓN"]
packages = [
    "com.discordapp.Discord",
]

["DESARROLLO"]
packages = [
    "com.dbeaver.DBeaverCommunity",
]

["DISEÑO Y CREATIVIDAD"]
packages = [
    "org.gimp.GIMP",
    "org.inkscape.Inkscape",
    "org.blender.Blender",
]

["UTILIDADES DEL SISTEMA"]
packages = [
    "com.github.tchx84.Flatseal",
    "io.github.flattool.Warehouse",
    "io.missioncenter.MissionCenter",
    "io.gitlab.adhami3310.Impression",
]

["SEGURIDAD Y PRIVACIDAD"]
packages = [
    "com.bitwarden.desktop",
]

["STREAMING Y REMOTO"]
packages = [
    "com.moonlight_stream.Moonlight",
    "com.github.iwalton3.jellyfin-media-player",
    "dev.lizardbyte.app.Sunshine",
]


["HERRAMIENTAS ADICIONALES"]
packages = [
    "org.openrgb.OpenRGB",
]

